#sudo apt-get update

#sudo apt-get install apache2

#sudo apt-get install mysql-server

#sudo apt-get install -yqq php libapache2-mod-php php-mcrypt php-mysql

#sudo nano /etc/apache2/mods-enabled/dir.conf (change index.html for index.php)

#sudo systemctl restart apache2

# Composer Install
# php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# php -r "if (hash_file('SHA384', 'composer-setup.php') === 'aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
# php composer-setup.php
# php -r "unlink('composer-setup.php');"

